env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - never
globals:
  pkg: readonly
  ags: readonly
  ARGV: readonly
  imports: readonly
  print: readonly
  console: readonly
  logError: readonly
